### ISSUE TITLE
02.txt 输出意见

### ISSUE THREAD

**Issue by NickChang97** [502408764/os-test-shell#7]
输入是02.txt
期望输出是
init A A A A B B B B E E E E E C A C

在那个cr E 2之后不是实时抢占的话，正在执行的进程应该是与前面相同的吧

**Comment by wanzhiwen** [comment]
第九行req R2 1这个命令把E给阻塞了吖

**Comment by NickChang97** [comment]
这个02.txt跟前面那个issue一个问题，如果cre E 2之后，E不处于运行态的话，正在执行的应该是B，所以req
R2 1是会让B阻塞，然后就会得到上面的那个期望输出

**Comment by wanzhiwen** [comment]
呃。。
