### ISSUE TITLE
05.txt输出意见

### ISSUE THREAD

**Issue by NickChang97** [502408764/os-test-shell#8]
05.txt  的期望输出
init a a a a b b b c d a a e e e c d a c d a
这个我不太确定，之前我询问了下老师，当时老师说的是to之后高优先级抢占，所以在cr e 2命令后
应该执行的还是当前执行的进程a.

**Comment by wanzhiwen** [comment]
emmm，我看指导书是每个命令后面都有schedule()，应该是每个命令执行完都调度一次把，不是to再调度吧。

**Comment by NickChang97** [comment]
如果每个命令执行完之后都schedule（）的话，那么测试用例就完全不对了吧，每次创建一个进程，不管它的优先级是啥那么一旦执行schedule就会切换进程，不存在每次创建一个进程之后当前运行进程不变的情况了

**Comment by wanzhiwen** [comment]
schedule不一定切换进程啊，如果正在运行的进程本来是高优先级且在队列前面就不用换了啊，它和to不一样。

**Comment by NickChang97** [comment]
我的问题，之前没有仔细读一下那个实验指导书中的schedule()伪代码，里面是这样的，我的理解不对，在每个kernel 函数之后都调用，而且在进程创建的时候也调用，但是老师之前跟我说的是to之后才抢占.....qwq
